### ISSUE TITLE
thread 'isahc-agent-42001' panicked

### ISSUE THREAD

**Issue by AurevoirXavier** [sagebind/isahc#295]
Is this a bug of isahc? I just:

```rust
for i in 0.. {
    http_client.send_async(request(i)).await?;
}
```
Then it:
```rust
// thread 'isahc-agent-42651' panicked at 'Receiver::next_message called after `None` 2021-01-29T10:50:51.263Z TRACE subalfred::substrate::github > 201
// ', /home/xavier/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.12/src/mpsc/mod.rs:1035:41
// note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
// Error: unknown error
//
// Caused by:
//     [26] Failed to open/read local data from file/application
```

**Comment by sagebind** [comment]
Thanks for filing an issue! First let's get some additional info so that I can help troubleshoot:

- What version of Isahc are you using?
- How is your HTTP client configured?
- Can you include a full backtrace of the error?

**Comment by AurevoirXavier** [comment]
1. `isahc = { version = "1.0.3", features = ["json"] }` 
1.
    ```rust
    pub fn new(oauth_token: impl AsRef<str>) -> Self {
    	let http_client = HttpClientBuilder::new()
    		.default_header("Authorization", &format!("token {}", oauth_token.as_ref()))
    		.build()
    		.unwrap();

    	Self { http_client }
    }
    ```
1.
    ```rust
    stack backtrace:
       0: rust_begin_unwind
                 at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:483
       1: core::panicking::panic_fmt
                 at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/core/src/panicking.rs:85
       2: core::option::expect_failed
                 at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/core/src/option.rs:1226
       3: futures_channel::mpsc::Receiver<T>::next_message
       4: <futures_channel::mpsc::Receiver<T> as futures_core::stream::Stream>::poll_next
       5: <sluice::pipe::chunked::Writer as futures_io::if_std::AsyncWrite>::poll_write
       6: <sluice::pipe::PipeWriter as futures_io::if_std::AsyncWrite>::poll_write
       7: <isahc::handler::RequestHandler as curl::easy::handler::Handler>::write
       8: curl::panic::catch
       9: curl::easy::handler::write_cb
      10: Curl_client_write
      11: Curl_readwrite
      12: multi_runsingle
      13: curl_multi_perform
      14: curl::multi::Multi::perform
      15: isahc::agent::AgentContext::run
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    Error: unknown error

    Caused by:
        [26] Failed to open/read local data from file/application

    Stack backtrace:
       0: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
       1: subalfred::main::main::{{closure}}
       2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
       3: std::thread::local::LocalKey<T>::with
       4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
       5: async_io::driver::block_on
       6: std::thread::local::LocalKey<T>::with
       7: async_std::task::builder::Builder::blocking
       8: subalfred::main
       9: std::sys_common::backtrace::__rust_begin_short_backtrace
      10: std::rt::lang_start::{{closure}}
      11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                 at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/core/src/ops/function.rs:259
          std::panicking::try::do_call
                 at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:381
          std::panicking::try
                 at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:345
          std::panic::catch_unwind
                 at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panic.rs:382
          std::rt::lang_start_internal
                 at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/rt.rs:51
      12: main
      13: __libc_start_main
      14: _start
    ```

**Comment by AurevoirXavier** [comment]
The request body is around 65536.

If I truncate it to 8192. That will increase the chance of success.

**Comment by sagebind** [comment]
Thanks, this is very helpful! Based on the stack trace, I think this might be caused by a bug in `sluice`. Could be similar to #72. I will look into it further when I have a chance.

**Comment by sagebind** [comment]
My hunch was correct; this appears to be a rare race condition bug in sluice: https://github.com/sagebind/sluice/pull/16. I will push a patch for sluice and a patch in Isahc that pulls in the fix shortly.
